const fs = require('fs');
let code = fs.readFileSync('src/pages/Reports.tsx', 'utf-8');

const targetStr = `                </div>
              </div>
            </div>
          </div>`;

const replacementStr = `                </div>
              </div>

              <div className="mt-auto pb-12 pt-16 w-full text-center border-t-2 border-slate-100">
                <p className="font-bold text-slate-800 text-xl mb-2">تم إنشاء هذا التقرير بواسطة منصة الأسعار العالمية</p>
                <p className="font-bold text-slate-500 text-lg">Generated by Global Prices Platform</p>
              </div>
            </div>
          </div>`;

code = code.replace(targetStr, replacementStr);
fs.writeFileSync('src/pages/Reports.tsx', code);
console.log('Fixed cover footer');
