const fs = require('fs');

let content = fs.readFileSync('src/pages/Reports.tsx', 'utf8');

// 1. Remove the background logo
content = content.replace(/<div className="absolute inset-0 z-0 flex items-center justify-center pointer-events-none"><ReportLogo url=\{logoUrl\} className="w-\[320px\] h-auto object-contain grayscale opacity-\[0.05\] report-logo" \/><\/div>/g, '');

// 2. Replace Header
const oldHeaderRegex = /<div className="flex justify-between items-center border-b-2 border-\[#1e3a8a\] pb-4 mb-8 relative z-10">\s*<div className="flex items-center gap-4">\s*<ReportLogo url=\{logoUrl\} alt="Logo" className="w-\[42px\] h-auto object-contain report-logo" \/>\s*<div>\s*<h4 className="font-bold text-\[#1e3a8a\] text-lg">شبكة ليبيا للتجارة - الأسعار العالمية<\/h4>\s*<h5 className="text-sm text-slate-500 font-medium">\{reportTitle\}<\/h5>\s*<\/div>\s*<\/div>\s*<div className="text-sm text-slate-500 font-medium font-mono" dir="ltr">\s*\{new Intl\.DateTimeFormat\('en-GB', \{ year: 'numeric', month: '2-digit', day: '2-digit' \}\)\.format\(new Date\(\)\)\}\s*<\/div>\s*<\/div>/g;

const newHeader = `<div className="flex justify-between items-center border-b-2 border-slate-200 pb-4 mb-8 relative z-10">
                  <div>
                    <h4 className="font-bold text-slate-800 text-lg">منصة الأسعار العالمية (GCP)</h4>
                    <h5 className="text-sm text-slate-500 font-medium">{reportTitle}</h5>
                  </div>
                  <div className="text-sm text-slate-500 font-medium font-mono" dir="ltr">
                    Page {++currentPageNum}
                  </div>
                </div>`;

let headerReplacements = 0;
content = content.replace(oldHeaderRegex, () => { headerReplacements++; return newHeader; });

// 3. Replace Footer
const oldFooterRegex = /<div className="absolute bottom-12 left-12 right-12 border-t-2 border-slate-200 pt-6 flex justify-between items-center text-xs text-slate-500 font-medium z-10 bg-white">\s*<div>\s*<p className="font-bold text-slate-800 text-sm mb-1">تم إنشاء هذا التقرير بواسطة منصة الأسعار العالمية<\/p>\s*<p className="font-bold text-slate-500">Generated by Global Prices Platform<\/p>\s*<\/div>\s*<div className="text-left font-bold text-slate-600">صفحة \{\+\+currentPageNum\} من \{totalPagesCount\}<\/div>\s*<\/div>/g;

const newFooter = `<div className="absolute bottom-12 left-12 right-12 border-t-2 border-slate-200 pt-6 flex justify-between items-center text-xs text-slate-500 font-medium z-10 bg-white">
                  <div className="flex flex-col">
                    <span className="font-bold text-slate-800 text-sm">© Libya Trade Network</span>
                    <span className="text-slate-600">Global Prices Platform (GCP)</span>
                  </div>
                  <div className="text-left font-bold text-slate-600" dir="ltr">Page {currentPageNum} of {totalPagesCount}</div>
                </div>`;

let footerReplacements = 0;
content = content.replace(oldFooterRegex, () => { footerReplacements++; return newFooter; });

fs.writeFileSync('src/pages/Reports.tsx', content, 'utf8');
console.log(`Update complete. Headers replaced: ${headerReplacements}. Footers replaced: ${footerReplacements}.`);
